name: C#

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1.88
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      with:
        submodules: 'true'
    - name: Build
      run: |
        cargo build --release --package uniffi-bindgen-cs

  test-bindings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      with:
        submodules: 'true'
    - name: Build test runner image
      run: docker build -t uniffi-bindgen-cs-test-runner .
    - name: Test bindings
      run: |
        docker run --rm \
          --volume $PWD:/mounted_workdir \
          --workdir /mounted_workdir \
          -e HOME=/root \
          uniffi-bindgen-cs-test-runner bash -c "source ~/.bashrc && ./build.sh && ./generate_bindings.sh && ./test_bindings.sh"
